### ISSUE TITLE
Figure out where to put recommendations?

### ISSUE THREAD

**Issue by vincerubinetti** [3b1b/3Blue1Brown.com#10]
Such a long word, really takes up a lot of space in the header. Perhaps put it on the "Extras" page? Or have it as a separate page, but don't link to it in the header, but instead link to it at the top of Extras or About with a big button?

**Comment by 3b1b** [comment]
We should have a "blog" part of the site, and this should simply live as a blog post.  It probably makes sense to treat such a blog just like the lessons.  At the moment there were just be two blog posts, but it's very likely there will be more.

Then the blog would pretty naturally live under "extras", unless it grows to deserve its own spot in the header.
