### ISSUE TITLE
Implement page transitions or get rid of next/link 

### ISSUE THREAD

**Issue by vincerubinetti** [3b1b/3Blue1Brown.com#101]
I use `next/link` in several places. I believe one of the uses of this\* is equivalent to `relative_url` from Jekyll or `relUrl` from Hugo: to prepend the baseurl to all relative links. But now we have the website setup such that it's always hosted from root and there is no baseurl.

Another use is to do faster client-side transitions between pages. That is, loading the contents of another page with javascript rather than actually navigating to it. This might make page switching a bit faster? And it allows for fancy transitions that we probably don't want anyway.

If neither of these use cases is applicable, we should just get rid of all the instances of me using `next/link` and just use regular old `<a>`.

\* Next doesn't seem to say it in the docs, but I'm making an assumption based on how routing works in other react libraries.

**Comment by PullJosh** [comment]
> This might make page switching a bit faster?

`next/link` does quite a bit of heavy lifting to make page transitions faster and much more lightweight. In particular, when switching between pages the only thing that is downloaded is the content of the page, but all the shared javascript code is reused.

The expectation is that you'll use `next/link` for all internal site links. They even have [an eslint rule](https://nextjs.org/docs/messages/no-html-link-for-pages) to enforce this.
