### ISSUE TITLE
Header grid background broken in Next

### ISSUE THREAD

**Issue by PullJosh** [3b1b/3Blue1Brown.com#104]
There's no 3D spinning grid here!

![image](https://user-images.githubusercontent.com/5458180/122852969-7953b100-d2df-11eb-8002-1d7c1f95f2b2.png)

Somehow during the transition to Next, the fancy 3D grid background got broken. Now it's super tiny and faint in the background.

Hopefully an easy fix? I'll take a stab at it sometime soon.

**Comment by vincerubinetti** [comment]
https://github.com/3b1b/3Blue1Brown.com/commit/377acd545dde993abe148dba75b1752541b44321
