### ISSUE TITLE
Change Figure Caption Styling

### ISSUE THREAD

**Issue by kurtbruns** [3b1b/3Blue1Brown.com#110]
- Remove italic font style from `figcaption` css
- Change `figcaption` to be lighter and also maybe smaller text

Currently, figure captions apply *italic* styling to its text. I think the italic styling should be removed and instead styled as lighter and maybe also smaller text.

The motivation here is to maintain the distinction between math variables in text, traditionally styled in italics, from regular font style while also having a stylistic different between captions and paragraph text.

**Comment by PullJosh** [comment]
@3b1b @kurtbruns I want to see what you think about this change.

## Before
![before](https://user-images.githubusercontent.com/5458180/124331699-be88a600-db5d-11eb-8e27-1755c825d52a.png)

## After
![after](https://user-images.githubusercontent.com/5458180/124331749-dc560b00-db5d-11eb-8d67-6999d2acd60b.png)

Good? Bad? Is there a tweak or change that would make it better?

**Comment by kurtbruns** [comment]
This looks great. The shade of grey looks to be on point.

There definitely is a trade-off between lighter and darker values of grey. Lighter text is less obtrusive and more stylistically different from the paragraph text, while darker text has better contrast with the background. Lighthouse may have a preference for higher contrast (darker) text when you run an audit.

I'd say we run with it as we can always circle back later!

**Comment by 3b1b** [comment]
Looks great to me.
