### ISSUE TITLE
Lesson topic grid design

### ISSUE THREAD

**Issue by PullJosh** [3b1b/3Blue1Brown.com#111]
**Simple solution:** When closing a right-side topic, the page should scroll back to a reasonable position.
**Better (harder) solution:** Implement Kurt's design, where the grid doesn't break apart as much when opening a topic.

![image](https://user-images.githubusercontent.com/5458180/123118783-ed41a680-d410-11eb-9fb8-abe837e26aec.png)

**Comment by kurtbruns** [comment]
I briefly revisited this issue this morning. Is there a design reason that we don't create a landing page for each topic group? See image below. This will surface a landing page that users can land on through organic search, is simple to implement and gives flexibility for handling collections vs. series.

![Topic Nav](https://user-images.githubusercontent.com/12160501/123128670-93d57980-d408-11eb-81f8-52d85e6f9fc5.png)

**Comment by PullJosh** [comment]
Separate pages for separate topics really appeals to me. This is worth discussing more as a group.

(Unrelated: What tool are you using to make these mockups?)

**Comment by kurtbruns** [comment]
The tool is [balsamiq](https://balsamiq.com/). Big fan, I think they have a 30-day trial if you are interested.
