### ISSUE TITLE
Add mailing list to bottom of all articles

### ISSUE THREAD

**Issue by PullJosh** [3b1b/3Blue1Brown.com#114]
The Substack email entry should be visible from lesson pages.

**Comment by PullJosh** [comment]
@3b1b How do you feel about this now that we added social media sharing links and stuff? The substack icon is already there, but not the embedded email input.

We could totally just add this as another thing at the bottom of each article, but then it starts to feel like too many calls to action. Which things should we prioritize?

**Comment by 3b1b** [comment]
What we have now looks perfect to me, thanks!
