### ISSUE TITLE
Contact form

### ISSUE THREAD

**Issue by PullJosh** [3b1b/3Blue1Brown.com#118]
There should be a contact form on the website which, when submitted, sends an email to Grant containing the message.

* Before submitting, users must check a box to confirm that their question isn't already answered in the FAQs.
* In the future there might be multiple types of forms (maybe one for fun questions and one for licensing and stuff) with slightly different behaviors.

**Comment by PullJosh** [comment]
I was originally planning to send emails using some kind of SMTP email service, but it looks like Netlify actually has a [forms](https://docs.netlify.com/forms/setup/) feature built-in. I've never used it before, but it seems like what we want.

**Comment by PullJosh** [comment]
Okay, I got Netlify Forms working well enough to test it out. Try filling out the form here: https://deploy-preview-124--3blue1brown.netlify.app/contact (The page you land on after submitting is currently just the Netlify default; don't worry too much about that for now.)

As a website owner, you can view all submissions within the Netlify dashboard under the "Forms" tab. You can also subscribe to new form submissions by email.

The upside of Netlify Forms is that it's nicely integrated and doesn't require setting up yet another account somewhere. The downsides I see are:
* Everyone who has access to the Netlify dashboard also has access to view all form submissions. I'm not sure how private/personal the messages you get are, but it's something to consider.
* Netlify Forms is [a bit pricey](https://www.netlify.com/pricing/#add-ons-forms) compared to other options. (We could probably sign up for a generic SMTP email service and use it to send emails to Grant for free, assuming submissions are on the order of ~100/day or less.)

At this point it's basically up to @3b1b. We can either:
* Use Netlify Forms, or...
* Sign up for an SMTP service, which can probably give us all the email sends we need for free. (I was playing around with sendinblue.com this morning and they give 300 daily emails for free.) Then create a serverless function to send an email for each form submission. The setup of this wouldn't be particularly hard; it would just be one more account & thing to manage.

**Comment by 3b1b** [comment]
Let's go with Netlify forms for the time being.

**Comment by 3b1b** [comment]
Probably the best way to do this is to have four separate contact forms, perhaps with each living inside an accordion to match the FAQs above it.

- Licensing inquiry
    - (Message)
    
    Under the standard YouTube license, you are free to embed the videos in your own site or blog, as long as it is not behind a paywall.
    
    If you want to use some of the visuals offline for classroom usage or a presentation, feel free to do so.  In both cases, attribution is of course appreciated.
    
    Otherwise, if you wish to license the videos to include in a commercial product, or to reupload in any way, kindly fill out the form below.

    - Name
    - Email
    - Organization name
    - Website
    - Are you seeking to license clips or full videos?
        - (Checkbox) Clips
        - (Checkbox) Full videos
    - Are you looking to license any of the following series?
        - Neural networks, 4 videos, ~1 hour
        - Calculus series, 12 videos, ~3.25 hours
        - Linear algebra series, 16 videos, ~3.2 hours
        - Differential equations, 6 videos, ~2 hours
    - Tell us more about what you're looking for
- Speaking request
    - Name
    - Email
    - Organization name
    - Approximate date for the desired talk
    - Estimated honorarium
    - Tell us more about what you're looking for
- Just want to say thanks
    - Name
    - Email
    - (Checkbox) Would you be comfortable with this note being shared anonymously with people who have helped or supported the channel?
    - Message
- General inquiry
    - Name
    - Email
    - (Checkbox) I am not asking a question that is answered in the FAQs above.
    - Message

**Comment by PullJosh** [comment]
@3b1b Are these forms designed the way you want? https://deploy-preview-124--3blue1brown.netlify.app/contact

Also, any thoughts on what the *thank you for your submission* screen should look like? (Currently it's just the Netlify default.)

**Comment by 3b1b** [comment]
That looks good to me. For the thank you, maybe for the last two we put

- "Thank you for the submission. All the messages are read, but we hope you understand not all can get a personal response."
