### ISSUE TITLE
Figure Resize Flash

### ISSUE THREAD

**Issue by kurtbruns** [3b1b/3Blue1Brown.com#129]
On page load and when an accordion is opened, sometimes figures flash a different size before calculating their final size. See the attached, slowed down video when opening an accordion. It happens quickly, but is noticeable and potentially distracting. Related to #107 cumulative layout shift score from lighthouse.

https://user-images.githubusercontent.com/12160501/123283050-3e60a180-d4c8-11eb-974e-05ab241c96dc.mp4

**Comment by PullJosh** [comment]
This might also be related to #119 (table of contents scrolling). I haven't properly tested it yet, but sizing figures using CSS only (as opposed to the current solution which also uses JS) might allow us to fix the table of contents scrolling bug as well as this one.
