### ISSUE TITLE
Lesson comments section

### ISSUE THREAD

**Issue by vincerubinetti** [3b1b/3Blue1Brown.com#13]
Choose safe and reliable comment service, such as Disqus or [some other service](https://github.com/greenelab/lab-website-template/wiki/Advanced-Editing#blog-post-comments). Then paste its embed code into the `comments.html` include.

Probably want to wait until the site is live to do this so we don't get comments on the in progress site, and because the page urls (which the services hook into) will change (e.g. `https://vincerubinetti.github.io/3Blue1Brown.com/lessons/test-lesson` -> `https://3blue1brown.com/lessons/test-lesson`).

**Comment by vincerubinetti** [comment]
This is homework for Grant, but I will also look into it to make a recommendation. I want to find a good service for my other projects as well.

**Comment by 3b1b** [comment]
Disqus actually looks pretty good, I say we go with that.  I've set up an account, but since it's billed on a per-month basis it probably makes sense to incorporate this only shortly before launching the site.

**Comment by vincerubinetti** [comment]
#42 incorps the built in disqus hugo plugin. When ready, I believe all you need to do is put your disqus id in the config file.
