### ISSUE TITLE
Home page design

### ISSUE THREAD

**Issue by 3b1b** [3b1b/3Blue1Brown.com#140]
After our discussion, I do agree that a slightly different home page landing experience could be better and that pulling out the featured lessons to be separate from the lesson gallery makes sense. It seems like there are potentially four things to include at the top of the home page.

- Brief words about what the site/channel is.
    - Possibility: "3blue1brown videos aim to illustrate the sense of creativity and discovery in math, presented with a highly visual style."
- Latest video
- Featured content
    - Maybe as a shelf beneath the top spotlight?
- Lesson gallery

The big benefit of the current single-video-in-the-spotlight vibe is its minimalism. This is potentially a nice way to set the tone of the minimalism of the content itself, which often aims to just display what is needed and nothing more. Even if we want to include all four things above, it would be best to do so in a way that still sets this tone.

@kurtbruns, if you have a chance, would you like to quickly throw together a wireframe or two to work from? I think the answer could be pretty simple, maybe just the words and latest video presented side-by-side up top, with a shelf of ~4 featured lessons below, followed by the lesson gallery. But sometimes the devil's in the details.

**Comment by 3b1b** [comment]
Nix the latest video.

Other possibilities.

- Spotlight contains social links and a mailing list
    - Maybe with words like "Want more math in your life?" above
- Spotlight contains some simple nice math visual.
    - Like [this](https://images.squarespace-cdn.com/content/v1/54f63048e4b0a47e92eb5234/1556304904556-CKU18YEJBJC5OTF4WPYA/FourierOfPi.gif?format=1000w)?

**Comment by 3b1b** [comment]
Okay, after mulling it over a bit more, here are some updated thoughts.

- I'm not positive the featured lessons should be separate from the lesson gallery, so let's leave it as; maybe it would be slightly better separate, maybe not, but it's marginal enough that our time spent implementing things and contemplating designs is better focused elsewhere.
- I don't think the latest video should be up there.
     - Insofar as the aim is to "show don't tell", i.e. give an example of what the channel/site is, that could be accomplished by having some nice math visual up there instead, something like [this gif](https://images.squarespace-cdn.com/content/v1/54f63048e4b0a47e92eb5234/1556304904556-CKU18YEJBJC5OTF4WPYA/FourierOfPi.gif?format=1000w).
     - Insofar as the aim is to have people landing on the site be updated about the latest, that might be better accomplished by inviting them to follow new videos in one of the many places they can do that.

Here's a sample of how that might look (forgive the scrappiness of my copy-paste spec-ing here)

![SampleHomePage](https://user-images.githubusercontent.com/11601040/123524642-97733580-d680-11eb-949a-3479b75b34af.png)

For a narrower screen, I might even just now show the gif.

Having the follow links in that spotlight adds some redundancy with what's at the bottom of the home page, as well as the header/footer, but that's a separate issue. The likely answer would simply be to nix what's at the bottom.

**Comment by 3b1b** [comment]
For those willing to tolerate my stream of consciousness on the matter, here's a potential tweak to the idea above.

- Let the intro graphic act as a preview to featured content.
    - This would mean we should remove the featured portion of the lesson gallery after all.
    - Have a nice animation (or react app) for each featured lesson.
    - Display those featured lessons in a slide-reel-like fashion in the spotlight.
    - Make clear that they can be either watched or read, to better signal that the site has written versions of content.
    - Given the motion involved in these spotlight animations, I think the page header with its swooping grid would benefit from being more subtle, say the size that it is on lesson pages.

![Attempt 2](https://user-images.githubusercontent.com/11601040/123560887-f3f65380-d759-11eb-96cd-62cd3e9c87cc.png)

A downside is that this currently has quite a few words, which may rob from the cleanliness and minimalism. Maybe this is outweighed by the benefits of being a bit more informative.

**Comment by kurtbruns** [comment]
Ok, I had some time today to start sketching. Here is one iteration that I think has some promise. It interleaves the three different views of the lesson content type with an overview of 3Blue1Brown. I personally feel that the "latest video" is a fine introduction for a brand new user, and works well for a returning user. Also, the "latest video" is fresh, minimal and demonstrates that 3Blue1Brown is about math educational content.

That being said, I'll read over the notes again tomorrow morning and make additional sketches that align better with the design talking points.

![home-page](https://user-images.githubusercontent.com/12160501/123578161-7438ab00-d792-11eb-9fe2-8bc8c2a8a932.png)

**Comment by kurtbruns** [comment]
For posterity's sake, here are the final forms of the wireframe: small tweaks from last night and a minimalist iteration.

Minimal version:

![3blue1brown-homepage-minimal](https://user-images.githubusercontent.com/12160501/123685368-d681c200-d80b-11eb-99cb-d4968cf375a1.png)

Small Tweaks:

![3blue1brown-homepage](https://user-images.githubusercontent.com/12160501/123685584-19439a00-d80c-11eb-80ef-b30f0e4bf954.png)

**Comment by PullJosh** [comment]
Note to self: use Grant's new topology video
