### ISSUE TITLE
Figure component autoplay and controls

### ISSUE THREAD

**Issue by 3b1b** [3b1b/3Blue1Brown.com#141]
- Videos currently autoplay as soon as they are in view, but really animations should only start when a user opts in by clicking play.
    - This behavior _is_ desirable in the case where a user toggles from "image" to "animation" in the figure component. In that case, it starts playing just after the toggle as it should.
- Also, it'd be better if the controls didn't pop up right when an animation is finished.

**Comment by PullJosh** [comment]
Gentler autoplay behavior is easy. 👍 But this...

> Also, it'd be better if the controls didn't pop up right when an animation is finished.

This is something that each browser does differently, and it isn't something we really have control over. (The only solution that I can think of is to use a custom video player instead of the built-in one, which is totally overkill.)

**Comment by 3b1b** [comment]
I was worried about that. I couldn't readily see what options might control that, but I wasn't sure if you knew anything magical. It's a pretty small niggle which we can ignore, though, so no big deal.
