### ISSUE TITLE
YouTube videos embedding at the top of lesson pages.

### ISSUE THREAD

**Issue by 3b1b** [3b1b/3Blue1Brown.com#142]
- At the moment, before playing the YouTube player, it shows the title and other info at the top which clutters things and is redundant with the title listed below. Moreover, when chapter numbers deviate it might actively conflict.

    <img width="1671" alt="Screen Shot 2021-06-27 at 2 34 05 PM" src="https://user-images.githubusercontent.com/11601040/123560085-1043c180-d755-11eb-804b-51de9c28d491.png">

    It looks like YouTube deprecated the embed parameter which hides that info, but perhaps we can simply show the thumbnail with a YouTube-style play button in the middle, like [this](https://kurzgesagt.org/portfolio/the-bacteriophage/).

- While I think the experience landing on the page to look around is nicer/more balanced if the embedded video is 70% width, the reason I opted for 100% is that once you're actually watching the video I believe it's nicer at 100%. I'm also not a fan of video embeds that force someone to click full screen to have a reasonable experience ([ahem](https://www.minutephysics.com/)).  If there's a natural and non-janky way to have the embed start at 70%, then expand upon being played, it may be worth exploring.

**Comment by PullJosh** [comment]
> Perhaps we can simply show the thumbnail with a YouTube-style play button in the middle

> If there's a natural and non-janky way to have the embed start at 70%, then expand upon being played, it may be worth exploring.

Maybe we could combine these? The placeholder thumbnail image is 70% size. When clicked, it expands into a full-width YouTube embed. Once you're viewing the embed, it always stays at 100% size to minimize jankiness.

**Comment by PullJosh** [comment]
I've got an implementation of this in #147. I think it's nice, but it would be good to get some other opinions.
