### ISSUE TITLE
Social links at end of article

### ISSUE THREAD

**Issue by PullJosh** [3b1b/3Blue1Brown.com#144]
We have social logo links in the footer (and soon on the homepage as well):
![image](https://user-images.githubusercontent.com/5458180/123677256-e2bd4d80-d812-11eb-909f-79021003b51e.png)

But most people who finish reading an article won't scroll to the bottom. So let's also include them at the end of the article, so that the sensation as a reader is that the social links are the very last piece of text contained within the article itself.

**Comment by PullJosh** [comment]
@3b1b I have a screenshot here of the social links from the footer. Is that what you want? Or do you want share buttons that help people spread each particular lesson on twitter/reddit/facebook/etc? (Also, should they appear in cases where there isn't a text version of the lesson?)

**Comment by 3b1b** [comment]
I think both. Perhaps something like "Enjoy this lesson? Consider sharing it: <button>" followed by something like "Want more math in your life?" with the links below.

At least for now, let's only have it in the case of lessons with written versions.

**Comment by PullJosh** [comment]
Right now I have share buttons generating posts like this:

![image](https://user-images.githubusercontent.com/5458180/124167160-bb17f080-da71-11eb-81a0-4dfbf78bf559.png)

(Only twitter is working so far.)

But we also have the option to include some text by default. Do you want to include any? If so, what should it say?

Also, would it be better to have links use 3b1b.co instead of 3blue1brown.com?

**Comment by PullJosh** [comment]
Okay, here's what it's looking like right now.

![image](https://user-images.githubusercontent.com/5458180/124169953-d5070280-da74-11eb-8362-29abe13a4813.png)

We could make each button a different color depending on the social network, but I actually kind of like the uniformity. Plus gray is a little less in-your-face.

It might be nice if you wrote some fun tooltip text for the share buttons just like you did for the social links.

**Comment by 3b1b** [comment]
Looks good, I agree gray is best. Feel free to merge, then I’ll think about content like tooltips in another branch.
