### ISSUE TITLE
Replace top-of-page lesson navigation

### ISSUE THREAD

**Issue by 3b1b** [3b1b/3Blue1Brown.com#148]
The articles may look cleaner without the navigation at the top. It's a feature I initially requested, but something feels off about the very first part of an article being an invitation for where else to go. It also breaks the visual flow a bit.

![image](https://user-images.githubusercontent.com/11601040/123843593-f0340f80-d8c6-11eb-8155-a12707e29dea.png)

Since we switched to having topic pages, perhaps another way to accomplish the same goal of easy navigation when landing on a page is to move the next/previous/topic functionality to buttons around the video itself, say like this.

![image](https://user-images.githubusercontent.com/11601040/123844507-f8d91580-d8c7-11eb-9b23-3e8cfd18eafa.png)

**Comment by PullJosh** [comment]
@3b1b I have an implementation of this in #150. Let me know how it looks to you.
