### ISSUE TITLE
Spotlight fixes

### ISSUE THREAD

**Issue by vincerubinetti** [3b1b/3Blue1Brown.com#16]
Pi creatures get covered up by video on small screens. Just remove.

Also per meeting on 5/9 we are getting rid of spotlight all together? Are we sure? Then there will be nothing directly watchable on the homepage.

**Comment by 3b1b** [comment]
On second thought, it is good to have the spotlight.

The pi creatures are fun to include, but let's just make them disappear (continuously?) when the screen width minus player width is too small.
