### ISSUE TITLE
Latex within question explanations

### ISSUE THREAD

**Issue by vivek3141** [3b1b/3Blue1Brown.com#161]
This could be a syntax issue on my end, but the latex doesn't seem to render within the explanations for questions

![image](https://user-images.githubusercontent.com/31397379/124030240-dc61d980-d9aa-11eb-9da4-fc62e10317a1.png)

![image](https://user-images.githubusercontent.com/31397379/124030320-ec79b900-d9aa-11eb-994b-356ad1e22194.png)

Here's my code:

```html
<Question
    question="If we begin with the configuration pictured above, what will happen?"
    choice1="The line will eventually end up rotating around the outer three points, only having hit the inside point a finite number of times."
    choice2="The line will hit all points an equal number of times before returning to its original position."
    choice3="The line will hit the inner point with every other switch."
    choice4="The line will cycle among the top three points, never hitting the bottom."
    answer={3}
>
    Correct! The inner point is hit once between every outer point, and so, it is hit $3-1=2$ times in one cycle. Refer to the animation below.
</Question>
```

**Comment by 3b1b** [comment]
Make sure there is a new line above and below the explanation, then the component will know to parse it as Markdown. That is, try this:

`<Question
    question="If we begin with the configuration pictured above, what will happen?"
    choice1="The line will eventually end up rotating around the outer three points, only having hit the inside point a finite number of times."
    choice2="The line will hit all points an equal number of times before returning to its original position."
    choice3="The line will hit the inner point with every other switch."
    choice4="The line will cycle among the top three points, never hitting the bottom."
    answer={3}
>

    Correct! The inner point is hit once between every outer point, and so, it is hit $3-1=2$ times in one cycle. Refer to the animation below.

</Question>`
