### ISSUE TITLE
Figure width Chrome vs Firefox

### ISSUE THREAD

**Issue by riverliway** [3b1b/3Blue1Brown.com#175]
The figures are different widths on Chrome compared to Firefox.

Edge appears to have the same width as Chrome.

I believe this only happens with SVG files, PNGs seem to be the same width.

Firefox:
![image](https://user-images.githubusercontent.com/82117023/124797382-0a916d00-df07-11eb-963a-2942ac12d041.png)

Chrome:
![image](https://user-images.githubusercontent.com/82117023/124797419-154c0200-df07-11eb-9d60-da8f580c69ce.png)

**Comment by PullJosh** [comment]
@riverliway Are you able to reproduce this issue now? I'm hoping that some of my recent changes might have fixed it, but I was never able to reproduce the problem on my machine in the first place.

**Comment by riverliway** [comment]
Just confirmed it on the live version at [https://www.3blue1brown.com/lessons/vectors](https://www.3blue1brown.com/lessons/vectors). The width now works as expected, thanks for the fix!
