### ISSUE TITLE
"Aside" component

### ISSUE THREAD

**Issue by vincerubinetti** [3b1b/3Blue1Brown.com#19]
Need some kind of footnote or aside component. There are several ways to do this.

One is by having a tooltip, but this is difficult and a bit hacky to do. Another is by having an accordion the reader can expand/collapse, but this, design wise, only makes sense for non-mid-sentence asides (it'd have to go after a full paragraph).

A perhaps temporary solution we came up with is: have a superscript icon or number that when clicked on expands a hidden paragraph below the current paragraph with rich content.

Need to experiment with this to figure out what the best doable solution is.

**Comment by 3b1b** [comment]
> A perhaps temporary solution we came up with is: have a superscript icon or number that when clicked on expands a hidden paragraph below the current paragraph with rich content.

I think this would work quite well, especially if the style (i.e. background color?) of the expanded portion was clearly distinct.
