### ISSUE TITLE
Redirects

### ISSUE THREAD

**Issue by 3b1b** [3b1b/3Blue1Brown.com#198]
Before swapping out the URL for 3blue1brown.com, we should make sure the following links work.

### These should point somewhere on the site itself
- [x] [/blog](https://deploy-preview-201--3blue1brown.netlify.app/blog)
- [x] [/podcast](https://deploy-preview-201--3blue1brown.netlify.app/podcast)
- [x] [/essence-of-linear-algebra](https://deploy-preview-201--3blue1brown.netlify.app/essence-of-linear-algebra) -> [Linear algebra topic page]
- [x] [/eola](https://deploy-preview-201--3blue1brown.netlify.app/eola) -> [Linear algebra topic page]
- [x] [/neural-networks](https://deploy-preview-201--3blue1brown.netlify.app/neural-networks) -> [Neural networks topic page]
- [x] [/nn](https://deploy-preview-201--3blue1brown.netlify.app/nn) -> [Neural networks topic page]
- [x] [/calculus](https://deploy-preview-201--3blue1brown.netlify.app/calculus) -> [Calculus topic page]
- [x] [/eoc](https://deploy-preview-201--3blue1brown.netlify.app/eoc) -> [Calculus topic page]
- [x] [/poems](https://deploy-preview-201--3blue1brown.netlify.app/poems) -> [???]
- [x] [/crypto](https://deploy-preview-201--3blue1brown.netlify.app/crypto) -> [???]
- [x] [/recommendations](https://deploy-preview-201--3blue1brown.netlify.app/recommendations)

### These should redirect with the same behavior as the current 3blue1brown.com, unless labeled otherwise here.
- [x] [/videos](https://deploy-preview-201--3blue1brown.netlify.app/videos) -> [https://www.youtube.com/3blue1brown]
- [x] [/support](https://deploy-preview-201--3blue1brown.netlify.app/support) -> [https://www.patreon.com/3blue1brown]
- [x] [/recommended](https://deploy-preview-201--3blue1brown.netlify.app/recommended) -> [https://www.youtube.com/playlist?list=PLZHQObOWTQDN52m7Y21ePrTbvXkPaWVSg]
- [x] [/store](https://deploy-preview-201--3blue1brown.netlify.app/store)
- [x] [/some1](https://deploy-preview-201--3blue1brown.netlify.app/some1)
- [x] [/SoME1](https://deploy-preview-201--3blue1brown.netlify.app/SoME1) (I assume things won't be case sensitive, but from Squarespace they evidently were...)
- [x] [/live](https://deploy-preview-201--3blue1brown.netlify.app/live)
- [x] [/ask](https://deploy-preview-201--3blue1brown.netlify.app/ask)
- [x] [/aops-3b1b](https://deploy-preview-201--3blue1brown.netlify.app/aops-3b1b)
- [x] [/plushie](https://deploy-preview-201--3blue1brown.netlify.app/plushie)
- [x] [/janestreet](https://deploy-preview-201--3blue1brown.netlify.app/janestreet)
- [x] [/questions](https://deploy-preview-201--3blue1brown.netlify.app/questions)
- [x] [/protocollabs](https://deploy-preview-201--3blue1brown.netlify.app/protocollabs)
- [x] [/remix](https://deploy-preview-201--3blue1brown.netlify.app/remix)
- [x] [/subscribe](https://deploy-preview-201--3blue1brown.netlify.app/subscribe)
- [x] [/brilliant](https://deploy-preview-201--3blue1brown.netlify.app/brilliant)
- [x] [/aops](https://deploy-preview-201--3blue1brown.netlify.app/aops)

### All of the walls of thanks, should point to the /#thanks portion of the appropriate video blog page.

- [x] [/quick-eigen-thanks](https://deploy-preview-201--3blue1brown.netlify.app/quick-eigen-thanks)
- [x] [/mat-exp-thanks](https://deploy-preview-201--3blue1brown.netlify.app/mat-exp-thanks)
- [x] [/bayes-factor-thanks](https://deploy-preview-201--3blue1brown.netlify.app/bayes-factor-thanks)
- [x] [/hamming-thanks](https://deploy-preview-201--3blue1brown.netlify.app/hamming-thanks)
- [x] [/monster-thanks](https://deploy-preview-201--3blue1brown.netlify.app/monster-thanks)
- [x] [/chess-thanks](https://deploy-preview-201--3blue1brown.netlify.app/chess-thanks)
- [x] [/ctracing-thanks](https://deploy-preview-201--3blue1brown.netlify.app/ctracing-thanks)
- [x] [/ldm-thanks](https://deploy-preview-201--3blue1brown.netlify.app/ldm-thanks)
- [x] [/pdf-thanks](https://deploy-preview-201--3blue1brown.netlify.app/pdf-thanks)
- [x] [/sir-thanks](https://deploy-preview-201--3blue1brown.netlify.app/sir-thanks)
- [x] [/beta1-thanks](https://deploy-preview-201--3blue1brown.netlify.app/beta1-thanks)
- [x] [/covid-thanks](https://deploy-preview-201--3blue1brown.netlify.app/covid-thanks)
- [x] [/bayes-thanks](https://deploy-preview-201--3blue1brown.netlify.app/bayes-thanks)
- [x] [/spiral-thanks](https://deploy-preview-201--3blue1brown.netlify.app/spiral-thanks)
- [x] [/windmill-thanks](https://deploy-preview-201--3blue1brown.netlify.app/windmill-thanks)
- [x] [/de4-thanks](https://deploy-preview-201--3blue1brown.netlify.app/de4-thanks)
- [x] [/de3-thanks](https://deploy-preview-201--3blue1brown.netlify.app/de3-thanks)
- [x] [/de2-thanks](https://deploy-preview-201--3blue1brown.netlify.app/de2-thanks)
- [x] [/de1-thanks](https://deploy-preview-201--3blue1brown.netlify.app/de1-thanks)
- [x] [/clacks-thanks](https://deploy-preview-201--3blue1brown.netlify.app/clacks-thanks)
- [x] [/sphere-thanks](https://deploy-preview-201--3blue1brown.netlify.app/sphere-thanks)
- [x] [/turbulence-thanks](https://deploy-preview-201--3blue1brown.netlify.app/turbulence-thanks)
- [x] [/quaternion-explorable-thanks](https://deploy-preview-201--3blue1brown.netlify.app/quaternion-explorable-thanks)
- [x] [/quaternion-thanks](https://deploy-preview-201--3blue1brown.netlify.app/quaternion-thanks)
- [x] [/dandelin-thanks](https://deploy-preview-201--3blue1brown.netlify.app/dandelin-thanks)
- [x] [/divcurl-thanks](https://deploy-preview-201--3blue1brown.netlify.app/divcurl-thanks)
- [x] [/alt-calc-thanks](https://deploy-preview-201--3blue1brown.netlify.app/alt-calc-thanks)
- [x] [/cramer-thanks](https://deploy-preview-201--3blue1brown.netlify.app/cramer-thanks)
- [x] [/wallis-thanks](https://deploy-preview-201--3blue1brown.netlify.app/wallis-thanks)
- [x] [/winding-thanks](https://deploy-preview-201--3blue1brown.netlify.app/winding-thanks)
- [x] [/basel-thanks](https://deploy-preview-201--3blue1brown.netlify.app/basel-thanks)
- [x] [/uncertainty-thanks](https://deploy-preview-201--3blue1brown.netlify.app/uncertainty-thanks)
- [x] [/fourier-thanks](https://deploy-preview-201--3blue1brown.netlify.app/fourier-thanks)
- [x] [/mug-thanks](https://deploy-preview-201--3blue1brown.netlify.app/mug-thanks)
- [x] [/nn3-thanks](https://deploy-preview-201--3blue1brown.netlify.app/nn3-thanks)
- [x] [/high-d-thanks](https://deploy-preview-201--3blue1brown.netlify.app/high-d-thanks)
- [x] [/btc-thanks](https://deploy-preview-201--3blue1brown.netlify.app/btc-thanks)
- [x] [/triples-thanks](https://deploy-preview-201--3blue1brown.netlify.app/triples-thanks)
- [x] [/leibniz-thanks](https://deploy-preview-201--3blue1brown.netlify.app/leibniz-thanks)
- [x] [/zeta-thanks](https://deploy-preview-201--3blue1brown.netlify.app/zeta-thanks)
- [x] [/topology-thanks](https://deploy-preview-201--3blue1brown.netlify.app/topology-thanks)

**Comment by PullJosh** [comment]
> I assume things won't be case sensitive, but from Squarespace they evidently were...

Netlify redirects are also case-sensitive. It seems like that's the standard for URLs in general. I added both `some1` and `SoME1`.

**Comment by PullJosh** [comment]
@3b1b What do you want to do for `/poems`, `/crypto`, and `/recommendations`? Recreate those pages on the new site?

**Comment by 3b1b** [comment]
- /poems should probably be a set of its own little blog posts(?)
- /crypto should probably just be recreated on the site, something super simple.
- /recommendations should point to a blog post with the same content plus a little more which I'll add later.

**Comment by 3b1b** [comment]
Also, for the podcast, we could make a simple component which is a shelf that also shows up on the home page, below lessons, consisting of the logo on the left with links for where to find it on the, carrying the same information as what's visible [here](https://anchor.fm/grant-sanderson).

The /podcast page could consist of this same component at the top, with video embeds of the latest episodes sitting below it.
