### ISSUE TITLE
Some ability to filter for lessons with written versions

### ISSUE THREAD

**Issue by PullJosh** [3b1b/3Blue1Brown.com#217]
Could be as simple as a tab or checkbox in the lessons gallery

**Comment by vincerubinetti** [comment]
At present, this feature is there.

<img width="297" alt="Screenshot 2024-05-28 at 6 06 31 PM" src="https://github.com/3b1b/3Blue1Brown.com/assets/8326331/75393090-11e7-4df1-b7a3-13c3c94794ac">

Could be improved, but I'll close.
