### ISSUE TITLE
Search bar

### ISSUE THREAD

**Issue by vincerubinetti** [3b1b/3Blue1Brown.com#24]
Method to search site for content. Related: https://github.com/greenelab/lab-website-template/issues/2

Probably just want to opt for an embedded google search. Grant will need to [register/create a search console](https://support.google.com/programmable-search/answer/4513903?hl=en) that we can paste into the template somewhere.

**Comment by 3b1b** [comment]
You mean something like this?

<script async src="https://cse.google.com/cse.js?cx=8dfbb53b83ef4c98e"></script>
<div class="gcse-search"></div>

The only thing I entered there was the URL www.3blue1brown.com, which presumably will be updated and re-indexed once we make the swap?

**Comment by vincerubinetti** [comment]
I don't know what the exact code will look like since I've never embedded a google search, but it should be something more than that. I'll look into it when we get to this.

**Comment by vincerubinetti** [comment]
![image](https://user-images.githubusercontent.com/8326331/120011727-9fba5100-bfac-11eb-8c16-6411b90f49b7.png)

Looks like there are a different ways to display it. You may end up with a few more code snippets to paste, but it seems like it'll be simple to just paste in wherever.

Let's think about where it belongs. My thoughts are: once on the homepage at the bottom, and once on the 404 page. I don't think it's necessary to put it in the header of every page, but it seems like that would be possible if we wanted.

**Comment by 3b1b** [comment]
"Copy the following code, and paste it into a div element in your site's body section, where you want both of the search box and the search results to render."

```
<script async src="https://cse.google.com/cse.js?cx=8dfbb53b83ef4c98e"></script>
<div class="gcse-search"></div>
```
