### ISSUE TITLE
Nametag Link is Incorrect

### ISSUE THREAD

**Issue by riverliway** [3b1b/3Blue1Brown.com#245]
**Describe the bug**
The attribution link in a lesson sends to the wrong link on the about page.

**Expected behavior**
The link for River sends to [https://www.3blue1brown.com/about#river-way](https://www.3blue1brown.com/about#river-way) but it should send to [https://www.3blue1brown.com/about#river-way-2021-intern](https://www.3blue1brown.com/about#river-way-2021-intern)

**Comment by RachaunH** [comment]
Hi, can I be assigned to this issue?

**Comment by 3b1b** [comment]
Fixed now.
