### ISSUE TITLE
Incorrect Podcast episode numbering

### ISSUE THREAD

**Issue by kilacoda** [3b1b/3Blue1Brown.com#246]
In the [podcast section](https://www.3blue1brown.com/podcast) of the site, episode 1 is labeled as episode 2, and episode 2 as episode 1:

![image](https://user-images.githubusercontent.com/65204531/127986689-dd69609c-9b6b-44c4-a037-c654a8932f00.png)

I think it might be due to the way they're ordered in [podcast.yaml](https://github.com/3b1b/3Blue1Brown.com/blob/main/data/podcast.yaml):

https://github.com/3b1b/3Blue1Brown.com/blob/74fcbf962c82cd4bfd536b4e3339c85a4935378e/data/podcast.yaml#L1-L7

**Comment by 3b1b** [comment]
Fixed now, thanks!
