### ISSUE TITLE
Emotive Pi Characters

### ISSUE THREAD

**Issue by PullJosh** [3b1b/3Blue1Brown.com#28]
Today we were talking about the value of the pi characters for expressing emotion.

It would be really great to have one or more components that enable us to use the pi characters to communicate emotion and whimsy. In particular, we discussed two ways the pi characters might be used:
1. To personify footnotes that contain little side points. Not all footnotes would have pi characters, but some could. It's worth considering this while implementing any footnote funcitonality.
2. Used inline with the regular body text to emphasize an emotional point. For example:
![image](https://user-images.githubusercontent.com/5458180/117880730-70020e00-b276-11eb-9c1e-72b287dfcd7e.png)
It would be cool for a pi character to make this exclamation.

Any component for these characters should definitely make it possible to specify the emotion of the pi character (as well as the associated text).

**Comment by vincerubinetti** [comment]
Can @3b1b or someone point me to the folder of pi creature svgs

**Comment by vincerubinetti** [comment]
https://www.dropbox.com/sh/x5dqd87cofrak63/AABrtc99MuXZrbQhPT6A4hlTa?dl=0
https://www.figma.com/file/klysuEehCnz9E6HqCqlfD6/PiCreatures?node-id=0%3A1
