### ISSUE TITLE
Error in question/answer in quiz in Essence of Linear Algebra - Chapter 6 The determinant

### ISSUE THREAD

**Issue by almeidayoel** [3b1b/3Blue1Brown.com#284]
Hi, 

In [Essence of Linear Algebra - Chapter 6 The determinant](https://www.3blue1brown.com/lessons/determinant) the first quiz question [What is the determinant of the following transformation?](https://github.com/3b1b/3Blue1Brown.com/blob/main/public/content/lessons/2016/determinant/determinant_scale_question.svg) should have determinant = -2 as per the given matrix but the explanation answer states 4 (-2 is not displayed in choices). 

It is also possible that the question contains an error and the matrix was intended to be
 **1   -1
 2     2**
This matches the actual values in visual representation in the question.
In that case, original answer of 4 would be right. 

![SharedScreenshot](https://user-images.githubusercontent.com/22722278/140934706-9eb8c4ab-175c-448a-ab58-eae6feda2365.jpg)

**Comment by riverliway** [comment]
Fixed in PR #295, thank you!
