### ISSUE TITLE
Discussion of image scaling and page width

### ISSUE THREAD

**Issue by KurtBruns** [3b1b/3Blue1Brown.com#32]
If we change the content width on the site to be a number with more factors than `1000`, such as `960` or `1080`, then it will make designing grid layouts and custom illustrations a little easier and IMO more pleasing. Namely, `1000` is missing the factor of `3`.

**Note:** This is pretty nit-picky since 1000px is perfectly fine. 

To illustrate why this might be nice, consider that `960` can be evenly divided by common numbers and the results also have a lot of factors too.

```
960/2 = 480
960/3 = 320
960/4 = 240
960/5 = 192
960/6 = 160
```

For completeness, shown below are the prime factorizations of the three numbers 960, 1000 and 1080.

```
960=2*2*2*2*2*2*3*5
```

```
1000=2*2*2*5*5*5
```

```
1080=2*2*2*3*3*3*5
```

**Comment by vincerubinetti** [comment]
This is easy to change and can be changed at any time without breaking anything.

I'm assuming you're concerned about image scaling. Some things to consider about that:

1. people often have their browser windows zoomed in/out, making the resolution not a perfect 1:1, necessitating scaling anyway
2. many people (like me) are using high pixel density displays where again 1 pixel does not equal 1 pixel
3. image scaling algorithms in browsers these days are very good and you probably wont notice

Basically, I recommend just making your images the way you want (doing it in dimensions with many factors or powers of 2 sounds good), and do it consistently among yourselves, and don't worry about how it gets scaled in the browser.

One thing I'll add is that, for the reasons above, you should rendering your images and videos at very high resolution, like 2x bigger than you expect them to appear in the final site. That way on retina displays they will still look crisp.

In general I wouldn't consider this a problem, but we can keep it open.
