### ISSUE TITLE
Typo in Calculus Chapter 3

### ISSUE THREAD

**Issue by Rasmion** [3b1b/3Blue1Brown.com#355]
Duplicate "the" _(but the the area)_

https://github.com/3b1b/3Blue1Brown.com/blob/a92bf93a6ebf71704dfc76dd8de2cbfdefdf90b0/public/content/lessons/2017/derivatives-power-rule/index.mdx#L277

**Comment by kurtbruns** [comment]
Thanks for pointing this out! It will be fixed once #353 is merged with the main branch.
