### ISSUE TITLE
Top of the lesson page layout

### ISSUE THREAD

**Issue by 3b1b** [3b1b/3Blue1Brown.com#36]
I'm just recording a few small notes here so I don't forget.

- Arguably the video embed should go above the title, dates, byline, etc. in the top of the lesson.
    - That way, when a person clicks on a lesson, what dominates the screen is an actual lesson rather than descriptors.
    - Having the title below the video also matches how its shows up on YouTube.  Not that they need to match, but it's a positive signal for the video-at-the-very-top design.
    - The title, dates, byline, etc. then serve as a kind of separator between video content and written content.
- Would it be crazy to have the video fill the full width of the page, analogous to the YouTube player's "theater mode"?
- Instead of displaying the group of the video below the byline, save the screen real estate and just don't display it at all, but maybe show it if someone clicks to open the lesson list (probably shown at the top of the list).
- Given that realistically it will take a while for most content to be bloggified, when there is no content in the markdown body (or even just if it's less than some threshold), we should not show the previous/next lesson bar at the bottom of the page due to the redundancy with the one at the top.
- Don't show the updated date when there's only a video and no written content.

<img width="1680" alt="Screen Shot 2021-05-14 at 11 00 11 PM" src="https://user-images.githubusercontent.com/11601040/118349895-6099f380-b508-11eb-9985-9589d42239cd.png">

**Comment by vincerubinetti** [comment]
> Arguably the video embed should go above the title, dates, byline, etc. in the top of the lesson.

Sounds good to me. You might still want the title above the video though, but this is all very easy to change in `_layouts/lesson.html`.

> Would it be crazy to have the video fill the full width of the page, analogous to the YouTube player's "theater mode"?

I think that'd probably be too wide, especially on desktop. I can demo that for you on a screen share call.

> Instead of displaying the group of the video below the byline,

That'd be okay with me. In general, the "details" section there is a bit verbose and busy, and I'm still searching for a cleaner way to display it all. Maybe the topic name could go as text next to the 
![image](https://user-images.githubusercontent.com/8326331/118372741-0f7a1600-b581-11eb-8aa5-f58f2bf16f65.png) 
icon in the button.

> Given that realistically it will take a while for most content to be bloggified
> Don't show the updated date

It sounds like you're planning to make the site go live before all the content is bloggified? If so there will need to be a few changes, including the ones you mentioned here. Another thing to add would be some kind of placeholder like "A text version of this lesson is coming soon!".
