### ISSUE TITLE
Extas page and site header organization

### ISSUE THREAD

**Issue by 3b1b** [3b1b/3Blue1Brown.com#37]
I'm Just leaving a note here for what content would be referenced on the extras page.  Completely open to suggestions on the best design surrounding it.

Stuff to put on extras page:

- [Interactive videos on quaternions](https://eater.net/quaternions)
- [Interactive(ish) versions of lockdown math lectures](https://itempool.com/3b1b)
- [MIT 18.S191](https://ocw.mit.edu/courses/mathematics/18-s191-introduction-to-computational-thinking-fall-2020/index.htm)
- [Multivariable calculus videos and article on Khan Academy](https://www.khanacademy.org/math/multivariable-calculus/)
- [TEDx Talk](https://www.ted.com/talks/grant_sanderson_what_makes_people_engage_with_math)
- [Ben, Ben and Blue](https://www.benbenandblue.com/)
- [Silly math poetry](https://www.3blue1brown.com/poems)
- [Contributions to Quanta](https://www.quantamagazine.org/authors/sandserson_grant/)
- I've tried to track contributions to other channels [here](https://www.youtube.com/playlist?list=PLZHQObOWTQDMhxE4XbNHLlJ56E2TGBZ0_).

**Comment by 3b1b** [comment]
Consolidation:
- Lessons
- Blog
- Podcast
- About
     - FAQ/Contact
     - What is 3blue1brown?
- Extras
- Follow (?)
    - Subscribe on YouTube
    - Mailing list
    - Twitter
- Support
    - Patreon
    - Store

**Comment by vincerubinetti** [comment]
How does the mailing list work, is there a link that I can put in the footer for that? That feels like another "social" link that belongs there.

For the "follow" and "support" header entry, since we already have all the icons in the footer, I'd just just 2-3 each that you really want to highlight.

**Comment by 3b1b** [comment]
I just set up a substack. We can link to [this page](https://3blue1brown.substack.com/p/welcome).

**Comment by 3b1b** [comment]
Okay, I know I keep going back and forth, but after lingering on it further I think your instincts are right to avoid sub-topics in the header, and that the relevant organization and surfacing of content should happen in another way.

The existing header is actually pretty good as is. The podcast and blog should only end up there if they earn their way there by having enough content. Until then, I think both should live at the top of the "extras" page, stylistically distinct from the cards which link out to external projects.

The mailing list living among the other "follow" items at the bottom of the home page should be a fine place for it to live.
