### ISSUE TITLE
Mismatch in the various figures for addition of vectors

### ISSUE THREAD

**Issue by julianharty** [3b1b/3Blue1Brown.com#381]
**Describe the bug**
This is a visual bug where there's a disagreement between the first three images showing vector addition versus the final one (where the end of the vector has `y=1`) 

**To Reproduce**
Steps to reproduce the behavior: visit: https://www.3blue1brown.com/lessons/vectors 

For me, the most obvious mismatch between the figures is between https://www.3blue1brown.com/content/lessons/2016/vectors/walk_path.svg (which shows the end of the vector is closer to `y=1.3` than `y=1` and https://www.3blue1brown.com/content/lessons/2016/vectors/vector_addition_numerical.svg which is more correct, the end point is roughly `y=1`.

**Expected behavior**
I'd appreciate vector _w_ being drawn consistently using the value of the vector shown in the last of the relevant figures, i.e. with a `y=-1` rather than being drawn with `y` being closer to `-0.3`. Doing so would make the already wonderful material more congruent.

**Screenshots**
Here's a screenshot showing the first two examples of the figures that have the reduced `y` value for vector _w_.
![Screenshot 2023-12-28 at 11 28 19](https://github.com/3b1b/3Blue1Brown.com/assets/785891/6ba5a507-8cbb-4901-b15c-98222a4bb2a0)

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma 14.1
 - Browser: Google Chrome, 
 - Version: 119.0.6045.159 (Official Build) (arm64)

**Additional context**
Here are the extracts from https://github.com/3b1b/3Blue1Brown.com/blob/main/public/content/lessons/2016/vectors/index.mdx 

```
<Figure
  image="vector_addition_prep.svg"
/>
```
```
<Figure
  image="vector_addition.svg"
  video="vector_addition.mp4"
/>
```
```
<Figure
  image="walk_path.svg"
/>
```

**Remarks**
I'm aware these pages are to provide additional support to the videos which aren't necessarily going to be re-recorded. Thank you so much for providing them.

**Comment by kurtbruns** [comment]
Hi Julian,

Thank you for pointing out this small mismatch. The vectors should match exactly when the whole linear algebra series is finished and merged into the main branch. For now, you can preview the incoming changes here:

https://deploy-preview-357--3blue1brown.netlify.app/lessons/vectors#addition
