### ISSUE TITLE
Many images not working

### ISSUE THREAD

**Issue by Fernando9200** [3b1b/3Blue1Brown.com#382]
**Describe the bug**
Many images are not being displayed.

**To Reproduce**
Visit: https://www.3blue1brown.com/lessons/essence-of-calculus

**Expected behavior**
The images should work.

**Screenshots**
![image](https://github.com/3b1b/3Blue1Brown.com/assets/91075845/0cffec31-5acc-4860-ab78-d6dfa9773490)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Google Chrome
 - Version 120

**Comment by kurtbruns** [comment]
Hey! I wasn't able to reproduce this, are you still having problems seeing the images from your end?

**Comment by Fernando9200** [comment]
Hi! I'm sorry for wasting your time, it seems that it was a local problem. It works now.

**Comment by kurtbruns** [comment]
No problem, thanks for checking!
