### ISSUE TITLE
Workflow Development

### ISSUE THREAD

**Issue by KurtBruns** [3b1b/3Blue1Brown.com#40]
# Goals

Our workflow should be robust, easy to us and leverage the benefits of `git` and Github.

I.e. an author in a local environment should be able to view and make changes without worrying about the live site or data constraints. Then, when it comes time to push changes to the live site, they are able to publish changes quickly and confidently through a pull request.  They should also have the ability to roll back to a previous commit.

## Current Workflow

Currently we use [Github Actions](https://docs.github.com/en/actions) to publish the live site to [Github Pages](https://pages.github.com/). We also use [Vercel](https://vercel.com/) to preview the site via a pull request. This workflow is simple, easy to use and well integrated into Github.

Due to high number of expected users, we plan to use store large static assets such as images and animations (.mp4, .mov, .png) on a Cloud Object Storage service. The proposed workflows below are suggestions for how we can extend our current workflow to use buckets.

## A Simple Workflow

This workflow uses two buckets called `development` and `production`.

While editing content, authors interact with the `development` bucket to add/edit/delete files. This would be done through the [Linode CLI](https://www.linode.com/docs/guides/linode-cli/) or [Cyberduck](https://www.linode.com/docs/guides/how-to-use-object-storage/#cyberduck). I tested this workflow using Cyberduck and it is easy to setup and use. We would mirror the `_posts` directory structure in the bucket.

To push changes to the live site, a pull request is created that generates a preview of the site with assets that use the `development` bucket. Then, either through manual action, a script or github action, the `production` bucket is synced with the `development` bucket and the pull request is merged.

Considerations:

- Assets live outside of git.
- Checking out a specific version of the site is difficult.

A solution for the two considerations above is to take a snapshot of the `production` bucket before a pull request is merged. This snapshot would be saved with the commit hash and would allow us to recover/roll the live site back to a previous commit.

## A Better Workflow*

This workflow has authors edit and commit large assets into VCS. Github actions would be used orchestrate local, staging and production environments using feature branches, a `development` branch and a `main` branch.

The author would edit local markdown files and assets that live next to each other.

```
example-post/
├── YYYY-MM-DD.md
├── animation-1.mp4
├── animation-2.mp4
├── figure-1.png
├── figure-2.png
├── ...
```

When the author is satisfied with their changes they  push to the `development` branch. This creates a development site available at a public URL. If the author wants to roll back changes,  they can revert to a specific commit and push to the `development` branch again.

Once changes have been staged in the development branch, a pull request for the `main` branch is created. Once accepted, this applies the changes in the development branch to the live site. This is the same workflow as pushing changes to the `development` branch.

### Technical Details

This workflow uses [git large file storage](https://git-lfs.github.com/) in combination with [Linode Object Storage](https://www.linode.com/docs/guides/how-to-use-object-storage/) (see #38) to manage the static files in two buckets: a development bucket and a production bucket. When pushing changes to the `development` or `main` branch a git action is run that syncs the bucket with the current commit.

See [s3 sync action](https://github.com/jakejarvis/s3-sync-action) as an example.

The local site would serve local assets while authoring content using something like [Jekyll Environments](https://jekyllrb.com/docs/configuration/environments/). These assets would be published in the build directory for the `local`, but not the `development` or `production` environments. I know this is possible in Hugo #34 , but may not be with Jekyll.

**Comment by KurtBruns** [comment]
After sleeping on it, my take is that we should go with the simple approach. That way we can start converting posts to markdown as early as today.

The simple workflow then can evolve naturally into the more robust version over time or as the robust version is developed.

**Comment by vincerubinetti** [comment]
Notes on Git LFS from my coworkers who have used it a lot:

> Be sure to run git lfs track file.txt  before adding the file to the commit, but then you can handle everything else normally I think. If you forget and commit before you do lfs-track then it’s in the commit history forever and causes a world of pain

> i think there is a monthly bandwidth limit per account: https://docs.github.com/en/github/managing-large-files/versioning-large-files/about-storage-and-bandwidth-usage 
that applies to other people downloading files that you’ve uploaded using git-lfs IIRC, i’ve run into issues with it on some old non-greenelab repos
not sure if we pay to extend it

> they have given us an exception as a scholarly team
we complained to them back in the day and they gave us either 2TB or 20TB/mo forever

**Comment by 3b1b** [comment]
Notes from our conversation this morning; feel free to correct if I'm saying the wrong things.

- We start by using git-lfs for all things pre-production.
- We'll then add a GitHub action that syncs the status of files as seen on lfs with a single Linode bucket whenever changes are merged with master, with some environment variable dictating where to look for files.
    - Note, this means nixing the development bucket mentioned above.  Might as well use lfs for everything where bandwidth is no concern.  We can revisit the idea of an intermediate bucket if issues seem to arise.
- Insofar as any development depends on whether we use Jekyll vs. Hugo, hold off until we make a final decision there; plenty of content work to be done in the meantime.
- Keep notes on any necessary git-lfs setup for newcomers (seems straightforward).

Further thoughts

- Back of the envelope estimations.  The topology article had ~20 MB of media.  After compression, though, it was closer to 8 MB.  So for every 100,000 post views, that would be ~800 Gigabytes of bandwidth.
     - This is a sample size of 1, and other posts will be longer/shorter/richer/lighter, but I suspect it's actually a decent representative of a "typical" post.
     - I suspect more visually rich posts will also be the ones with more traffic.
     - In the future, there's room to optimize where we only serve an animation when it's requested, but for now, let's stick with what's simplest and make further judgments only when we have actual user data.
     - As a side note, this means the compressed version of the full library could be around 1 GB.
- On the topic of compression, we should probably keep the highest quality versions of all media in the repo as "ground truth", then if possible have compression take place when the files are all being synced with the Linode bucket.
- When creating content, no one should be thinking about data constraints.  The more visually rich, as long as it is in the service of a better learning experience, the better.

**Comment by vincerubinetti** [comment]
> On the topic of compression, we should probably keep the highest quality versions of all media in the repo as "ground truth", then if possible have compression take place when the files are all being synced with the Linode bucket.

This is definitely something we can and should automate. I believe Kurt said that Hugo has some of these compression features built-in.

**Comment by KurtBruns** [comment]
Update on the progress on this issue:

The `workflow` branch is currently setup to run an action that syncs the contents of the `test` directory with the Linode bucket. For example, the file

```
test/a.txt
```

is synced to the URL

```
https://3b1b-posts.website-us-east-1.linodeobjects.com/test/a.txt
```

## Test Workflow

To test the action, download [`git lfs`](https://git-lfs.github.com/), install the extension and then checkout the `workflow` branch. Make and commit changes (add/edit/delete) to the `test` directory. To trigger the action, push the changes to the origin and watch the action run on Github in the *actions* tab.

**Note:** Files that are deleted from the `test` directory will also be deleted from the bucket on sync.

Examples of `git lfs` and bucket URLS can be found by serving the site locally and sorting the lessons by date. I created a *git LFS test* post which uses the `title-animation.mp4` file in the `test` directory. 

## Next Steps

Integrating this action with the deploy action should be relatively straight forward. (1) Decide on the publish directory structure, (2) update the figure component and (3) update the deploy workflow.

1) Publish bucket assets to a known location. For example, assets could be published to the `_site/media` directory which would then be synced with the bucket url `bucket-url/media/`. To prevent these assets from also being published to Github pages, an ignore rule would be added to the `gh-pages` branch `.gitignore`.

2) Update the figure component to be environment aware.

	- For local development, the `media` directory is used for the asset's URL as in `http://localhost:4000/media/example.mp4`. 
	- For previewing a pull request, the `git lfs` URL and the current branch name is used for the asset's URL.
	- For the live environment, the bucket URL is used like the local environment.

3) Integrate the sync action into the deploy workflow. In the `.github/workflows/sync-test.yaml` file I have the Jekyll build step commented out. I haven't tested it yet, but it should work fine. Once setup, we should make sure that the `media` directory from (1) is successfully ignored.

## Notes

The `git lfs` URL contains the branch name of the file. For example, the URL contains the `workflow` branch.

```
https://github.com/3b1b/3Blue1Brown.com/raw/workflow/test/title-animation.mp4
```
In order to preview a version of the site, I think we can set a branch environment variable that gets passed to the build step. But maybe we skip this for now and get the deploy action working first.

**Comment by KurtBruns** [comment]
Note for (1) above. The sync actions supports pattern matching files, so we could also sync certain files types instead of the whole directory.

I.e. assets could live next to .html files, the source directory for the sync action would be something like `_site/lessons` and the `.gitignore`  on the `gh-pages` branch would have rules like `lessons/**/*.mp4`.

**Comment by KurtBruns** [comment]
I spent some time tinkering over the weekend with this action on a personal Hugo project and that implements the above steps. There was a couple of hiccups, but the action works perfectly and is ready to be implemented here to finish the workflow. However, I'll wait until the dust settles on #42
