### ISSUE TITLE
Could i contribute even though I do not get the internship?

### ISSUE THREAD

**Issue by Matheart** [3b1b/3Blue1Brown.com#41]
Dear Grant, even though I do not have the internship opportunity, could I still make some contributions on this project? Thank you!

**Comment by Matheart** [comment]
.

**Comment by 3b1b** [comment]
Hi Matheart, thanks for the generous offer.  For the moment, while we're still working out the full process, both in terms of the underlying tooling and in terms of content principles, it will be much easier to develop as an "in-house" operation.

Once both of those are clearer, it may be worth opening things up to more contributions (e.g. for translations).  Feel free to check back in in a month or so.
