### ISSUE TITLE
Distinguish series from non-serial groups

### ISSUE THREAD

**Issue by 3b1b** [3b1b/3Blue1Brown.com#45]
Some groups of topics (linear algebra, calculus, differential equations, neural networks) are meant to be a contiguous series, whereas all the others are more just collections of topics with similar topics/genres.  It might make sense for the design under the "by topics" tab to reflect this.

Then, for those groups which are meant to be series, it might make sense to display the chapter numbers with a separate design around their titles.

**Comment by vincerubinetti** [comment]
#44
