### ISSUE TITLE
404 Page Search Link is Broken

### ISSUE THREAD

**Issue by riverliway** [3b1b/3Blue1Brown.com#59]
Currently the 404 page has a link to the search page, but the link is https://3blue1brown.netlify.app/search%20%7c%20relURL%20, which serves another 404 page because of the extra characters at the end of the search URL.

**Comment by vincerubinetti** [comment]
Thanks for bringing this up, fixed in: https://github.com/3b1b/3Blue1Brown.com/commit/0e5d8db952e232095c3ee2fe6e89d7c45aca42f5
