### ISSUE TITLE
Table of Contents Bug

### ISSUE THREAD

**Issue by riverliway** [3b1b/3Blue1Brown.com#92]
I have a width related bug with the table of contents. Not sure if its everyone or just me. I found it on Chrome, not sure if it also happens on other browsers

How to replicate:
Start on the lessons page.
Go to 256 Bit Security article.
Scroll down until the table of contents pops out
Hit the back button on your browser. (Don't click the lessons button or try to navigate to the lessons page, it must be the back button.)

Then the region where the TOC was is white and you can't remove it until refreshing the page.
![image](https://user-images.githubusercontent.com/82117023/122452907-9e05fc80-cf5e-11eb-9053-d598a4d6a371.png)

I tried it with the Chapter 1 calculus article and this bug didn't happen. I'm not sure why it happens on some and not on others.

**Comment by vincerubinetti** [comment]
I did experience this once, I believe I know the issue. Will fix.
