### ISSUE TITLE
Table of Contents Hiding Suggestion

### ISSUE THREAD

**Issue by riverliway** [3b1b/3Blue1Brown.com#94]
When I hide the table of contents and then scroll up & back down, it comes back into view. Can we make it so it remains hidden until the user chooses to have it be shown again?

**Comment by vincerubinetti** [comment]
I can make it so once the user interacts with the TOC once, that disables the automatic behavior until the page is reloaded. @3b1b thoughts?

**Comment by 3b1b** [comment]
That sounds like the correct solution to me

I just wrote this among several other thoughts in https://github.com/3b1b/3Blue1Brown.com/issues/97. I know the table of contents was a bit involved to wrangle with, thanks for bearing with the iteration.
