### ISSUE TITLE
Center align figure caption

### ISSUE THREAD

**Issue by riverliway** [3b1b/3Blue1Brown.com#95]
When the caption for an image is 1 line, it is centered. When it is multiple lines then it is left justified. 

![image](https://user-images.githubusercontent.com/82117023/122468358-7881ee80-cf70-11eb-87ce-2849bba63b11.png)

![image](https://user-images.githubusercontent.com/82117023/122468385-820b5680-cf70-11eb-8de8-414fc0a1ec79.png)

I'm not sure if this was intentional or not, but I feel like the left justified caption doesn't separate itself from the article content enough. Can we make the multiline captions either middle justified or smaller width so it is clear that the caption is not part of the article text?

**Comment by vincerubinetti** [comment]
This is intended behavior. 

I think justified text looks better when there is more of it, like below. One thing I will do is decrease the width of the caption to make it distinct. It also is italic which provides further distinction:

![image](https://user-images.githubusercontent.com/8326331/122472131-29e34d00-cf8e-11eb-8841-a84b33e8cbf6.png)
