### ISSUE TITLE
Latex equation numbering & scroll bar

### ISSUE THREAD

**Issue by riverliway** [3b1b/3Blue1Brown.com#96]
One of my math blocks has equation numbering and a scroll bar on it. I think it is because I used an `align` environment to make sure the equal signs are aligned. Can we disable equation numbering for a specific math block?

![image](https://user-images.githubusercontent.com/82117023/122469157-779d8c80-cf71-11eb-9b51-e5bd30bed902.png)

Here is my latex:
$$
\begin{align}
\text{Energy}&=(hf)(\color{blue}1\color{black})^2
\\ &= (hf)\left(\color{green}\sqrt{1/2}\color{black}\right)^2+(hf)\left(\color{red}\sqrt{1/2}\color{black}\right)^2
\end{align}
$$

I don't think the scroll bar should be there regardless of the equation numberings though.

**Comment by vincerubinetti** [comment]
It looks like there are a few ways to do it, one of them being using an `*` in your align tags:
https://tex.stackexchange.com/questions/2597/how-do-i-turn-off-equation-auto-numbering

See if that works. According to one of those answers, an additional package might need to be installed.

I'll look at the katex css to see if I can remove the scroll bar. Note that the scroll bar still may be needed for wide equations on mobile screens:
https://github.com/KaTeX/KaTeX/issues/327
