### ISSUE TITLE
Table of contents unfolding

### ISSUE THREAD

**Issue by 3b1b** [3b1b/3Blue1Brown.com#97]
When the table of contents unfolds, rather than nudging the article contents to the side it might be better to have the contents remain centered with the table just being in the margin. I think the intent was to keep the margin on either side of the article equal, but I think the overall effect current is to make things feel more off-balance.

I remember asking for the toc to unfold upon scrolling down, but if I had also asked for the bump to the article, then my apologies.

As an added bonus, this should help with items in the right margin not getting kicked off-screen:
![image](https://user-images.githubusercontent.com/11601040/122472102-f9db8000-cf74-11eb-84e7-d230ff6dfab3.png)

A few other thoughts, all of which can be considered lower priority:

- If the panel is closed, then scrolling up then down should not result in it coming back
- When shrinking the window from wide enough to not wide enough, it should transition to the table closed state rather than remaining on the table open state and transitioning to the dark mode. That is, article content takes precedence over toc content.
- Maybe put the "x" to close the panel on the inside rather than outside, so it doesn't poke out into article space.  Perhaps have the closing icon show up above section titles, which is how google docs seem to do it: 
![image](https://user-images.githubusercontent.com/11601040/122472509-8b4af200-cf75-11eb-8a29-d92e53f0cc35.png)

**Comment by vincerubinetti** [comment]
> I remember asking for the toc to unfold upon scrolling down, but if I had also asked for the bump to the article, then my apologies.

You didn't request this specifically, but wikiwand does it and I was emulating that.

> When shrinking the window from wide enough to not wide enough, it should transition to the table closed state 

I can add this but keep in mind for future things like this: this thing you and I do, resizing the window to various sizes, is for testing. In my experience most people don't do this regularly on a page; the page just stays the size it was when it loaded, based on the user's device and preferred zoom level.

**Comment by 3b1b** [comment]
I think one of the concerns is that the transition feels a little jarring, especially if you're actually reading the article as it happens.

> when you get to the bottom and the toc would overlap the footer

Ah, I see what you're saying.  How would you feel if the footer content width then just matched the article width?

> In my experience most people don't do this regularly on a page; the page just stays the size it was when it loaded, based on the user's device and preferred zoom level.

100% agree; I should have emphasized this is an even lower priority than the others. It's possible I'm a bit weird, but I do often resize windows to go from full screen to half screen as I'm interacting with sites and pulling up something separate for notes.

**Comment by vincerubinetti** [comment]
> How would you feel if the footer content width then just matched the article width?

I'll play with it but in my mind it looks a bit awkward, especially on shorter pages, because the header doesn't (and can't) do the same thing. I might just try the `upEnough`, or just letting it overlap.

> even lower priority than the others

I figured you were aware, just wanted to say it out loud just as a general comment for future things.
